require('./stylesheets/base.scss')
require('./images/tech-radar-landing-page-wide.png')
require('./images/merico-logo.svg')
require('./images/merico-logo-favicon.png')
require('./images/search-logo-2x.svg')
